package.json, src/approval/collectCommitsForPR.test.ts, src/client.ts, src/client/GraphQLClient/client.test.ts, src/client/GraphQLClient/response.ts, src/client/OrganizationAccountClient.ts, src/config.ts, src/steps/index.test.ts, src/sync/converters.ts, src/types/client.ts, src/types/integration.ts, src/util/createGitHubAppClient.ts, src/util/sha.ts, src/validateInvocation.test.ts, test/config.ts, test/recording.ts, yarn.lock
Hi @mknoedel !
So here is a cleanup rebuild of the previous PR that doesn't have any fake secrets in the git history.
The problem that is keeping it from passing the tests is something to do with authentication and the Polly recordings. The tests all pass with a local var.
The good news is that we're on the latest version of the @octokit modules now. 
--Kevin
=> Rebuild of previous pr typingLessons for gitleaks

CHANGELOG.md, src/client/GraphQLClient/fragments.ts, src/client/GraphQLClient/types/client.ts, src/sync/converters.test.ts, src/sync/converters.ts, src/types/entities.ts
Closes JupiterOne/integrations#5
=> Use name || login for displayName

CHANGELOG.md, package.json, src/client.ts, src/client/OrganizationAccountClient.ts, src/client/OrganizationAccountClientErrors.test.ts, src/config.ts, src/steps/pullrequests.ts, src/sync/converters.ts, test/config.ts, yarn.lock
Check Commit messages for what was done.
Tested in the development environment and it was successful
=> SDK v2 release

CHANGELOG.md, docs/jupiterone.md, package.json, src/steps/__snapshots__/index.test.ts.snap, src/steps/index.test.ts, src/sync/converters.ts, yarn.lock
Per Jira-1640 https://jupiterone.atlassian.net/browse/INT-1640 , we'd like to change the `role` property of outside collaborators to `OUTSIDE`.
@aiwilliams for review.
=> Change role values

CHANGELOG.md, src/steps/pullrequests.ts
These errors look like `Step "Fetch Pull Requests" failed to complete due to error. (errorCode="UNEXPECTED_ERROR", errorId="a4b083bb-570f-4f59-8e76-53026396e4df", reason="Unexpected error occurred executing integration! Please contact us in Slack or at https://support.jupiterone.io if the problem continues to occur.")` in the logs which is really unhelpful.
=> Add error logging to the pull request step.

CHANGELOG.md, src/client.ts, src/client/OrganizationAccountClient.ts
Hi @mknoedel !
Here you go!
--Kevin
=> More robustness for one repo fail scenarios

CHANGELOG.md, docs/jupiterone.md, src/client.ts, src/config.ts, src/getStepStartStates.ts, src/index.ts, src/sync/converters.ts
Hi @mknoedel !
Here are scope improvements.
--Kevin
=> Scopes checking improvement for environments

CHANGELOG.md, src/client/OrganizationAccountClient.ts
Current errors look like this 
`Step "Fetch Repos" failed to complete due to error. (errorCode=undefined, errorId="34ba2d9c-8a68-41b5-acbf-d4e60aa7f633", reason="")`
=> log graphql error messages properly

docs/jupiterone.md, src/client.ts, src/client/OrganizationAccountClient.ts, src/config.ts, src/getStepStartStates.ts
Hi @mknoedel !
Here's the scope fix.
--Kevin
=> Env scope update

CHANGELOG.md, src/client/GraphQLClient/client.ts, src/client/OrganizationAccountClient.ts
There was some broken processing in this error handler that's preventing us from getting good info on the real error.
=> Fix undefined error fail

src/client/GraphQLClient/client.ts
Merge this too. :)  A little more robust catch of GraphQL API errors returned via [200] code
=> Catching more Github API errors

CHANGELOG.md, package.json, src/client/GraphQLClient/client.ts, yarn.lock
=> Rate limiting now respects resetAt

CHANGELOG.md, src/client/GraphQLClient/client.ts
=> Ints 70 adding logs

src/client/GraphQLClient/client.ts, src/client/GraphQLClient/response.test.ts, src/client/GraphQLClient/response.ts
There were 2 problems with the graphQL response cursing:
1. Only the base-level query cursor was getting read, which meant any child-level cursing was getting ignored.
2. Only the base-level resource was being used when determining there was a next page or not, which was preventing repos from getting ingested.
Passed against dev locally
=> Fix Graphql children cursor retry logic

CHANGELOG.md, src/client.ts, src/client/GraphQLClient/client.ts, src/client/OrganizationAccountClient.ts
Hi @mknoedel or @austinkelleher !
Here is an update to handle the ETIMEDOUT node error and move the sleep function out of the retry logic.
=> Int 2216 catch etimedout node error

CHANGELOG.md, src/client.ts, src/client/GraphQLClient/__recordings__/GitHubGraphQLClient-fetchOrganization-childOnly_806475663/recording.har, src/client/GraphQLClient/__recordings__/GitHubGraphQLClient-refreshTokenInFetchOrg-childOnly_3957261641/recording.har, src/client/GraphQLClient/client.test.ts, src/client/GraphQLClient/queries.ts, src/client/GraphQLClient/refreshToken.test.ts, src/client/OrganizationAccountClient.ts, src/steps/issues.ts, src/steps/pullrequests.ts, src/steps/teamMembers.ts, src/steps/teamRepos.ts
Three fixes:
-- shared team names per INT-120
-- tests updated to use the single-team queries that the code is using
-- Issues updated to accept collaborators as creators or assignees
Enjoy!
=> Int 120 fix for shared team names

src/client/GraphQLClient/response.ts
=> Fix prop name in hack

.prettierignore, package.json, src/client/GitHubApp.test.ts, src/client/GitHubApp.ts, src/index.ts, src/sync/fixtures/pullRequest.ts, src/types/client.ts, src/util/getInstallation.ts, src/util/propertyHelpers.test.ts, src/util/sha.test.ts, yarn.lock
- update SDK to 8.4.1
- add format:check
- Formatted all code
=> Prep ticket work

CHANGELOG.md, src/config.ts
This work allows for the managed environment to provide two ways of authentication: 
1. the existing OAuth
2. Installing and configuring a GitHub App. This will be used for GitHub Server Enterprise. (see below)
=> Updates to support managed environment.

.gitignore, CHANGELOG.md, README.md, package.json
Using beta in version to indicate that these changes are in trial.
=> Release v1.12.0-beta.1

package.json, src/client/GraphQLClient/client.ts, src/client/GraphQLClient/errorHandlers.ts, yarn.lock
- Add additional verbose logging in GraphQL client
- Add handleTimeout to GraphQL client
- Upgrade sdk packages to 8.12.1
=> Introduce retry logic for timeouts in GraphQL client

CHANGELOG.md, docs/development.md, docs/jupiterone.md, package.json
Plus a few documentation changes
=> Release v1.15.0

src/steps/__snapshots__/vulnerabilityAlertsSteps.test.ts.snap, src/steps/vulnerabilityAlertsSteps.ts, src/sync/converterUtils.test.ts, src/sync/converterUtils.ts, src/sync/converters.ts
Fixes a undefined error and replaces direct relationship with mapped relationship
=> Int 383 fix&relationship

CHANGELOG.md, src/steps/__snapshots__/vulnerabilityAlertsSteps.test.ts.snap, src/steps/vulnerabilityAlertsSteps.ts, src/sync/converters.ts
Converting relationship between vuln and cwe/cve to be a mapped relationship.
=> INT-4057 - Converting to mapped relationship

CHANGELOG.md, src/actions/actionExecutionHandler.ts, src/actions/partialIngestActionHandler.ts, src/config.ts
Clean up config, unused githubInstallationId value
=> Clean up - final 

src/steps/pullRequests.ts
Skipping both the entity creation and relationship creation if we get a duplicate PR.
=> Skipping potentially duplicate relationship creation

package.json, src/client.ts, src/getStepStartStates.ts, yarn.lock
- Add disabled reasons to getStepStartStates.ts
=> Update integration-sdk-* to 8.18.0

src/steps/__snapshots__/vulnerabilityAlertsSteps.test.ts.snap, src/sync/converters.ts
INT-4110 requested a few property name changes.
The clearly identified one was addressed here. 
Other changes will be addressed in a separate PR and/or ticket.
=> Update GitHub Finding property names

src/client.ts, src/steps/branchProtectionRules.ts, src/steps/envSecrets.ts, src/steps/environments.ts, src/steps/orgSecrets.ts, src/steps/repoSecrets.ts, src/steps/repos.ts, src/sync/converters.test.ts, src/sync/converters.ts, src/types/entities.ts, test/recording.ts
This PR will add Github Pages ingestion to this integration. If the installed application has `Repository Permissions` for `Pages` set to `Read-Only`, the following properties will be added to the `github_repo` entity:
* hasPages
* pagesUrl
I have tested against my own installation with permissions enabled and am seeing the properties being added. I also confirmed that this does not break existing installations that do not yet have these permissions enabled.
=> Int 5677 ingest pages

CHANGELOG.md, jupiterone/questions/questions.yaml, src/client/GraphQLClient/fragments.ts, src/client/GraphQLClient/issueQueries/__snapshots__/IssuesQuery.test.ts.snap, src/client/GraphQLClient/repositoryQueries/__snapshots__/OrgRepositoriesQuery.test.ts.snap, src/client/GraphQLClient/teamQueries/__snapshots__/TeamsQuery.test.ts.snap, src/client/GraphQLClient/types/client.ts, src/steps/__snapshots__/repos.test.ts.snap, src/sync/converters.ts, src/types/entities.ts
| Property     | Type     |
| ------------ | -------- |
| `visibility` | `string` |
=> IDEA-950 - Add repo visibility to `github_repo`
